title: "UMS demo"
description: "UMS demo"
baseurl: "" # 루트 배포
url: "https://jkarvis91.github.io/umspages"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

include:
  - _includes
exclude:
  - README.md
  - node_modules
