title: ""
description: "UMS demo"
baseurl: "/umspages" # 루트 배포
url: "https://jkarvis91.github.io"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: layout

include:
  - _includes
exclude:
  - README.md
  - node_modules
